version: '2.0'

services:
  db:
    image: sameersbn/postgresql:10-2
    container_name: webapp_flask_postgres
    restart: always
    environment:
      - DEBUG=false
      - DB_TEMPLATE=postgres
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=webapp_flask_db
    volumes:
      - ${PWD}/docker/db:/var/lib/postgresql
    ports:
      - 6000:5432